In [39]:
## Handling Imbalnced Dataset 

#using : Up sampling
#        Down Sampling

Upsampling

In [40]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [41]:
n_class_0,n_class_1    # class_0 is 900 , class_1 is 100 , 

####  upsampling using this try to make class_1 900 and class_0 100 so both get balanced

(900, 100)

In [42]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [43]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)
print(df)

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

[1000 rows x 3 columns]

In [44]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [45]:
## apply upsampling 

df_minority = df[df['target']==1]
df_majority = df[df['target'] == 0]

In [46]:
### use library  : resample to create more sample for minory one

from sklearn.utils import resample

df_minority_unsampled = resample(df_minoriy, replace = True,
                                   n_samples = len(df_majority), random_state = 42)

In [47]:
df_minority_unsampled.shape

(900, 3)

In [48]:
df_minority_unsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [49]:

df_upsampled = pd.concat([df_majority, df_minority_unsampled])

In [50]:
df_upsampled['target'].value_counts() 
 ## here now 0 = 900, 1= 900 so minority also changes to 900 

##  so here both get balanced by upsampling

target
0    900
1    900
Name: count, dtype: int64

### Downsampling

In [51]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [52]:
n_class_0,n_class_1

(900, 100)

In [53]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [54]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)
print(df)

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

[1000 rows x 3 columns]

In [55]:
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [56]:
## apply Downsampling : 

df_minority = df[df['target']==1]
df_majority = df[df['target'] == 0]

In [ ]:
### use library  : resample to reduce the sample from majority by replace = False

from sklearn.utils import resample

df_majority_downsampled = resample(df_majority, replace = False,
n_samples = len(df_majority), random_state = 42)

In [ ]:
df_majority_downsampled.shape   # 900 rows , 3 colmns

(900, 3)

In [59]:
df_majority_downsampled.head()

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0

In [60]:
df_downsampled = pd.concat([df_majority, df_majority_downsampled])

In [61]:
df_downsampled.target.value_counts()

target
0    1800
Name: count, dtype: int64